//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("VMLib")]
[assembly: AssemblyDescription("Virtual Machine Control Library.")]
[assembly: AssemblyCompany("Wil Taylor")]
[assembly: AssemblyProduct("VMLib")]
[assembly: AssemblyVersion("0.0.0.2")]
[assembly: AssemblyFileVersion("0.0.0.2")]
[assembly: AssemblyCopyright("Copyright Wil Taylor 2016")]
[assembly: ComVisible(false)]

