//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("VMLib")]
[assembly: AssemblyDescription("Virtual Machine Control Library.")]
[assembly: AssemblyCompany("Wil Taylor")]
[assembly: AssemblyProduct("VMLib")]
[assembly: AssemblyVersion("0.1.1.125")]
[assembly: AssemblyFileVersion("0.1.1.125")]
[assembly: AssemblyCopyright("Copyright Wil Taylor 2016")]
[assembly: ComVisible(false)]

[assembly: InternalsVisibleTo("VMLib.UnitTest")]
[assembly: InternalsVisibleTo("VMLib.VMware.UnitTest")]
[assembly: InternalsVisibleTo("VMLib.VirtualBox.UnitTest")]
[assembly: InternalsVisibleTo("VMLib.HyperV.UnitTest")]

